-- ベーステーブルの作成
CREATE TABLE IF NOT EXISTS packets
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    timestamp  TIMESTAMPTZ NOT NULL,
    node_id    SMALLINT    NOT NULL,
    raw_packet BYTEA,
    CONSTRAINT packets_pkey PRIMARY KEY (id, timestamp)
);

-- パケット詳細テーブルの作成
CREATE TABLE IF NOT EXISTS packet_details
(
    packet_id   BIGINT,
    timestamp   TIMESTAMPTZ NOT NULL,
    src_mac     MACADDR     NOT NULL,
    dst_mac     MACADDR     NOT NULL,
    ether_type  INTEGER     NOT NULL,
    src_ip      INET        NOT NULL,
    dst_ip      INET        NOT NULL,
    src_port    INTEGER,
    dst_port    INTEGER,
    ip_protocol INTEGER     NOT NULL,
    data        BYTEA,
    CONSTRAINT fk_packets FOREIGN KEY (packet_id, timestamp) REFERENCES packets (id, timestamp)
);

-- packetsテーブルをハイパーテーブルに変換 (1時間ごとのチャンク
SELECT create_hypertable('packets', 'timestamp', chunk_time_interval => INTERVAL '1 hour');

-- ノードIDとタイムスタンプに対するインデックス (raw_packetを含む
CREATE INDEX idx_packets_node_timestamp_included ON packets (node_id, timestamp DESC) INCLUDE (raw_packet);

-- タイムスタンプに対する単純な降順インデックス
CREATE INDEX idx_packets_timestamp ON packets (timestamp DESC);
